from __future__ import annotations

import uuid
from typing import Any

from aidlc.bus import RedisBus, wait_for_redis
from aidlc.models import AgentTask, utc_now
from aidlc.settings import settings
from aidlc.skills import STAGE_SKILLS, architecture_payload


PIPELINE = [
    ("dev", "DEVELOPMENT", STAGE_SKILLS["DEVELOPMENT"]),
    ("qa", "TESTING", STAGE_SKILLS["TESTING"]),
    ("review", "REVIEW", STAGE_SKILLS["REVIEW"]),
    ("deploy", "DEPLOYMENT", STAGE_SKILLS["DEPLOYMENT"]),
]


def task_id(run_id: str, role: str) -> str:
    return f"{run_id}:{role}:{uuid.uuid4().hex[:8]}"


def execute_run(bus: RedisBus, run_id: str) -> None:
    state = bus.get_run(run_id)
    if state is None:
        return
    request = state["request"]
    shared: dict[str, Any] = {
        "repository": request["repository"],
        "base_branch": request["base_branch"],
        "requirement_file": request["requirement_file"],
        "execution_mode": request["execution_mode"],
    }
    results: dict[str, Any] = {}
    try:
        bus.update_run(run_id, status="PLANNING")
        bus.event(run_id, "REQUIREMENT", "hermes-orchestrator", "OpenSpec requirement context loaded")
        bus.event(run_id, "PLAN", "hermes-orchestrator", "Created Dev → QA → Review → Deploy task graph")
        for role, stage, skill_names in PIPELINE:
            task = AgentTask(
                task_id=task_id(run_id, role), run_id=run_id, role=role,
                stage=stage, skill_names=skill_names, payload=shared,
            )
            bus.update_run(
                run_id, status=stage, current_agent=f"hermes-sf-{role}", current_task=task.task_id,
            )
            bus.event(
                run_id,
                stage,
                "hermes-orchestrator",
                f"Dispatching {task.task_id} to hermes-sf-{role} / 正在分派任务至 hermes-sf-{role}",
                "DISPATCH",
                {"task_id": task.task_id, "target": f"hermes-sf-{role}", "skills": skill_names},
            )
            bus.submit_task(task)
            result = bus.wait_result(task.task_id)
            results[role] = result.model_dump()
            shared.update(result.outputs)
            bus.event(
                run_id,
                stage,
                "hermes-orchestrator",
                f"Gate evaluated for {task.task_id}: {'PASS' if result.passed else 'DENY'} / 门禁判定完成",
                "PASS" if result.passed else "DENY",
                {"task_id": task.task_id, "source": f"hermes-sf-{role}"},
            )
            if not result.passed:
                decision = "DENY" if role != "deploy" else "ALLOW_PR_WITH_DELIVERY_WARNING"
                if role != "deploy":
                    bus.update_run(
                        run_id, status="FAILED", final_decision=decision, results=results,
                        current_agent="hermes-orchestrator", current_task=None,
                    )
                    return
        pull_request = None
        if request["execution_mode"] == "live" and settings.github_write and shared.get("pushed"):
            from aidlc.gitops import create_pull_request

            pull_request = create_pull_request(
                request["repository"], shared["branch"], request["base_branch"],
                "AIDLC OpenSpec change / AIDLC OpenSpec 变更",
                "Generated by Hermes agents. Deterministic QA and review gates passed. Human approval is required.\n\n由 Hermes Agent 生成，已通过确定性 QA 与评审门禁，仍需人工审批。",
            )
            bus.event(run_id, "PULL_REQUEST", "hermes-orchestrator", f"Created PR #{pull_request['number']}")
        bus.event(run_id, "EVIDENCE", "hermes-orchestrator", "Evidence Pack sealed / 证据包已封存")
        delivery_result = results.get("deploy", {})
        delivery_passed = bool(delivery_result.get("passed"))
        delivery_mode = delivery_result.get("outputs", {}).get("delivery", {}).get("mode")
        if pull_request and delivery_passed and delivery_mode == "real":
            final_decision = "ALLOW_PR_AND_PREVIEW"
        elif pull_request and not delivery_passed:
            final_decision = "ALLOW_PR_WITH_DELIVERY_WARNING"
        elif pull_request:
            final_decision = "ALLOW_PR"
        else:
            final_decision = "ALLOW_PREVIEW" if delivery_passed else "DENY"
        evidence = {
            "schema_version": "3.0",
            "run_id": run_id,
            "generated_at": utc_now(),
            "architecture": architecture_payload(),
            "request": request,
            "selected_skills": {stage: skills for _, stage, skills in PIPELINE},
            "results": results,
            "pull_request": pull_request,
            "events": bus.events(run_id),
            "final_decision": final_decision,
        }
        bus.save_evidence(run_id, evidence)
        bus.update_run(
            run_id, status="COMPLETED", final_decision=final_decision,
            pull_request=pull_request, results=results,
            current_agent="hermes-orchestrator", current_task=None,
        )
    except Exception as exc:
        bus.event(run_id, "FAILED", "hermes-orchestrator", f"{type(exc).__name__}: {exc}", "ERROR")
        bus.update_run(
            run_id, status="FAILED", final_decision="DENY", error=f"{type(exc).__name__}: {exc}",
            current_agent="hermes-orchestrator", current_task=None,
        )


def run_orchestrator() -> None:
    bus = wait_for_redis()
    while True:
        run_id = bus.next_run()
        if run_id:
            execute_run(bus, run_id)
